# Generated by Django 4.1.7 on 2024-01-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_temp_billing_resturant_items_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resturant_items',
            old_name='kitchen',
            new_name='kitchen_nam',
        ),
    ]
