# Generated by Django 4.1.7 on 2024-01-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_temp_billing_bill_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='bills_no',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField()),
            ],
        ),
    ]
