# Generated by Django 4.1.7 on 2024-01-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_bills_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bills_no',
            old_name='bill_no',
            new_name='billing_no',
        ),
    ]
