# Generated by Django 4.1.7 on 2024-01-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_rename_bill_no_bills_no_billing_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_order_no',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_order_nos', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='temp_billing',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
