# Generated by Django 4.1.7 on 2024-01-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_resturant_items_total_item_wise_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturant_items',
            name='qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
