# Generated by Django 4.1.7 on 2024-01-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_resturant_items_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='total_kitchen_wise_amt',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
