# Generated by Django 4.1.7 on 2024-01-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_kitchen_total_kitchen_wise_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
